/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	import flexUnitTests.MyTestSuite;
	import flexUnitTests.tests.BitHackerTest;
	import flexUnitTests.tests.ComponentTest;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		private var flexUnitTests_tests_BitHackerTest_obj:flexUnitTests.tests.BitHackerTest;
		private var flexUnitTests_tests_ComponentTest_obj:flexUnitTests.tests.ComponentTest;
		private var flexUnitTests_MyTestSuite_obj:flexUnitTests.MyTestSuite;
	}
}